// ─── All user-facing copy of the public roadmap (English; ready for later i18n) ───

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`

export const S = {
  nav: {
    skip: "Skip to content",
    primary: "Main navigation",
    feedback: "Feedback",
    roadmap: "Roadmap",
    changelog: "Changelog",
    board: "Board",
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
    rss: "RSS feed",
    poweredBy: "Feedback board",
  },

  common: {
    retry: "Try again",
    tryAgain: "Try again",
    back: "Back",
    loading: "Loading",
    anonymous: "Anonymous",
    team: "Team",
    optional: "Optional",
    close: "Close",
    seeAll: (n: number) => `See all ${n}`,
    ideas: (n: number) => plural(n, "idea", "ideas"),
    votes: (n: number) => plural(n, "vote", "votes"),
    comments: (n: number) => plural(n, "comment", "comments"),
    updates: (n: number) => plural(n, "update", "updates"),
    goHome: "Back to all boards",
  },

  errors: {
    generic: "Something went wrong. Please try again.",
    network: "We couldn't reach the server. Check your connection and try again.",
    timeout: "The request took too long. Please try again.",
    notFoundTitle: "We couldn't find that page",
    notFoundBody: "The link may be old, or the page has moved. Head back and pick up from there.",
    loadFailedTitle: "This didn't load",
    rateLimited: (seconds: number | null) =>
      seconds ? `You're going a bit fast. Try again in ${seconds}s.` : "You're going a bit fast. Try again in a moment.",
    dailyLimit: "You've reached today's limit. Please come back tomorrow.",
    boundaryTitle: "Something went wrong",
    boundaryBody: "This page hit an unexpected problem. Reloading usually fixes it.",
  },

  home: {
    boardsTitle: "Choose a board",
    boardsHint: "Every product has its own board for ideas and progress.",
    openBoard: "Open board",
    noBoardsTitle: "No boards yet",
    noBoardsBody: "Boards will show up here as soon as they're published.",
    latestTitle: "Latest updates",
    allUpdates: "All updates",
    ctaFeedback: "Share an idea",
    ctaRoadmap: "See the roadmap",
    metaDescriptionFallback: "Vote on ideas, follow progress, and see what just shipped.",
  },

  feed: {
    searchLabel: "Search ideas",
    searchPlaceholder: "Search ideas",
    clearSearch: "Clear search",
    sortLabel: "Sort by",
    sort: { top: "Top", new: "New", trending: "Trending" },
    filters: "Filters",
    filtersTitle: "Filter ideas",
    filtersActive: (n: number) => `Filters, ${n} active`,
    status: "Status",
    tags: "Tags",
    clearFilters: "Clear filters",
    removeFilter: (name: string) => `Remove filter: ${name}`,
    showResults: "Show results",
    loadMore: "Load more",
    loadingMore: "Loading more",
    endOfList: "You've reached the end",
    emptyTitle: "No ideas here yet",
    emptyBody: "Be the first to suggest something. Good ideas start small.",
    emptyFilteredTitle: "Nothing matches",
    emptyFilteredBody: "Try a different search or clear the filters.",
    closedTitle: "This board isn't taking new ideas right now",
    closedBody: "You can still browse, vote and comment where enabled.",
    pinned: "Pinned",
    teamReplied: "Team replied",
    viewRoadmap: "View roadmap",
    roadmapCardTitle: "See what's coming",
    roadmapCardBody: "Planned and in progress ideas at a glance.",
    resultsFor: (n: number) => plural(n, "idea", "ideas"),
    suggestFab: "Suggest an idea",
    ownPendingTitle: (n: number) => (n === 1 ? "Your idea is awaiting review" : `${n} of your ideas are awaiting review`),
    ownPendingBody: "Only you can see it until the team approves it.",
  },

  vote: {
    // The visible text of the button is the vote count, so the accessible name must contain it (WCAG 2.5.3).
    label: (title: string, count?: number) => (count === undefined ? `Vote for: ${title}` : `${count} votes. Vote for: ${title}`),
    labelShort: (voted: boolean) => (voted ? "Remove your vote" : "Vote"),
    votedAnnounce: "Vote added",
    unvotedAnnounce: "Vote removed",
    closed: "Voting is closed for this idea",
    boardClosed: "Voting is turned off on this board",
    failed: "We couldn't save your vote. It has been reverted.",
    votesWord: "votes",
    voteInstead: "Vote instead",
    voted: "Voted",
    thanksVote: "Thanks, your vote was counted.",
    hiddenCount: "Vote",
  },

  submit: {
    heading: "Suggest an idea",
    subheading: "Tell us what would make this better. Search first to see if it already exists.",
    titleLabel: "Title",
    titlePlaceholder: "A short, specific summary",
    titleHint: (min: number, max: number) => `${min} to ${max} characters`,
    bodyLabel: "Details",
    bodyPlaceholder: "What problem does this solve? Any context that helps us understand.",
    nameLabel: "Your name",
    namePlaceholder: "Anonymous",
    nameHint: "Shown with your idea. Leave empty to stay anonymous.",
    tagsLabel: "Tags",
    tagsHint: (max: number) => `Pick up to ${max}`,
    submit: "Post idea",
    submitting: "Posting",
    counter: (n: number, max: number) => `${n}/${max}`,
    similarHeading: "Similar ideas",
    similarHint: "Vote for one of these instead of creating a duplicate.",
    similarSearching: "Looking for similar ideas",
    successApproved: "Thanks! Your idea is live.",
    successPendingReview: "Thanks! Your idea is waiting for a quick review and will show up once it's approved.",
    successPendingHold: "Thanks! Your idea was received and is being checked before it appears.",
    viewIdea: "View your idea",
    another: "Suggest another",
    tooFast: "Please take a moment and try again.",
    tooFastWait: (s: number) => `Try again in ${s}s`,
    duplicate: "You've already posted this. Please change it or check your earlier idea.",
    closed: "This board isn't accepting new ideas right now.",
    expiredRetry: "That took a while. Please press Post idea again.",
    validation: {
      titleMin: (n: number) => `Use at least ${n} characters.`,
      titleMax: (n: number) => `Keep it to ${n} characters or fewer.`,
      bodyMax: (n: number) => `Keep it to ${n} characters or fewer.`,
      nameMax: (n: number) => `Keep it to ${n} characters or fewer.`,
      commentMin: (n: number) => `Write at least ${n} characters.`,
      commentMax: (n: number) => `Keep it to ${n} characters or fewer.`,
    },
    honeypot: "Leave this field empty",
  },

  post: {
    backToBoard: (name: string) => `Back to ${name}`,
    by: "by",
    pendingTitle: "Awaiting review",
    pendingBody: "Only you can see this idea until the team approves it.",
    pendingCommentsTitle: (n: number) => (n === 1 ? "Your comment is awaiting review" : `${n} of your comments are awaiting review`),
    pendingCommentsBody: "It will appear here once approved.",
    mergedTitle: "Merged idea",
    mergedBody: (n: number) => `Idea #${n} was combined with this one. Its votes and comments now live here.`,
    responseTitle: "Official response",
    responseTeam: "Team",
    statusHeading: "Status",
    historyHeading: "Progress",
    historyCreated: "Idea posted",
    historyMoved: (from: string | null, to: string) => (from ? `${from} to ${to}` : `Set to ${to}`),
    detailsHeading: "Details",
    relatedHeading: "Shipped in",
    votesHeading: "Votes",
    shareHeading: "Share",
    copyLink: "Copy link",
    linkCopied: "Link copied",
    numberLabel: (n: number) => `Idea #${n}`,
    voteBarVotes: (n: number) => plural(n, "vote", "votes"),
  },

  comments: {
    heading: (n: number) => (n === 0 ? "Comments" : `Comments (${n})`),
    empty: "No comments yet. Start the conversation.",
    closed: "Comments are turned off for this board.",
    loadMore: "Load more comments",
    reply: "Reply",
    cancelReply: "Cancel reply",
    replyingTo: (name: string) => `Replying to ${name}`,
    formLabel: "Add a comment",
    placeholder: "Share your thoughts",
    post: "Post comment",
    posting: "Posting",
    successApproved: "Comment posted.",
    successPending: "Thanks! Your comment is waiting for review and will appear once approved.",
    failed: "We couldn't post your comment. Please try again.",
    replies: (n: number) => plural(n, "reply", "replies"),
    teamBadge: "Team",
  },

  roadmap: {
    title: "Roadmap",
    subtitle: "What we're planning, building and shipping.",
    emptyColumn: "Nothing here yet",
    tabsLabel: "Roadmap stages",
    ideasInStage: (n: number) => plural(n, "idea", "ideas"),
    featureOff: "The roadmap isn't available for this site.",
  },

  changelog: {
    title: "Changelog",
    subtitle: "New features, improvements and fixes as they ship.",
    rss: "Subscribe via RSS",
    emptyTitle: "Nothing published yet",
    emptyBody: "Product updates will appear here.",
    filterAll: "All",
    filterLabel: "Filter by type",
    boardFilter: "Board",
    allBoards: "All boards",
    label: { new: "New", improved: "Improved", fixed: "Fixed" },
    readMore: "Read more",
    backToChangelog: "Back to changelog",
    relatedIdeas: "Ideas shipped in this update",
    loadMore: "Load older updates",
    featureOff: "The changelog isn't available for this site.",
  },

  footer: {
    contact: "Contact us",
    rights: (name: string, year: number) => `© ${year} ${name}`,
  },

  meta: {
    homeTitle: (site: string) => site,
    boardTitle: (board: string, site: string) => `${board} feedback | ${site}`,
    boardDescription: (board: string) => `Vote on ideas and follow progress for ${board}.`,
    roadmapTitle: (board: string, site: string) => `${board} roadmap | ${site}`,
    roadmapDescription: (board: string) => `See what's planned, in progress and shipped for ${board}.`,
    postTitle: (post: string, board: string, site: string) => `${post} | ${board} | ${site}`,
    changelogTitle: (site: string) => `Changelog | ${site}`,
    changelogDescription: (site: string) => `The latest updates, improvements and fixes from ${site}.`,
    notFoundTitle: (site: string) => `Page not found | ${site}`,
  },
} as const
